# Complex_moments_and_exceptions_in_the_function_call_stack_Python
Цель: понять как работают исключения внутри функций и как обрабатываются эти исключения на практике при помощи try-except.  Задача "План перехват"
